### ISSUE TITLE
Us State border in Us Map counties

### ISSUE THREAD

**Issue by soundaridss** [VictorCazanave/svg-maps#123]
State border is not adding in this counties us map. Please help me how to draw/add state border in the counties us map @avalladaresm

**Comment by VictorCazanave** [comment]
Sorry for my late reply, I recently have very little time to work on this project.

The [USA, Counties map](https://github.com/VictorCazanave/svg-maps/tree/master/packages/usa.counties) only contains the counties and their borders. If you want to see the state borders, you can use the [USA map](https://github.com/VictorCazanave/svg-maps/tree/master/packages/usa).
I think a map mixing state and county borders is out of the scope of this project. Then, you probably have to modify the SVG by yourself.
