### ISSUE TITLE
Guideline to create a custom maps

### ISSUE THREAD

**Issue by bladerunner2020** [VictorCazanave/svg-maps#2]
Is there any guideline how to create a custom maps?

**Comment by VictorCazanave** [comment]
Do you mean how to add a new map in this project or how to customize an existing map?

**Comment by bladerunner2020** [comment]
A new one.

**Comment by VictorCazanave** [comment]
There is a [contribution guide](https://github.com/VictorCazanave/svg-maps/blob/master/CONTRIBUTING.md) but it may be incomplete, so feel free to ask questions if needed 😃

**Comment by bladerunner2020** [comment]
Ok. I managed to create my map, but have couple of questions:
1. I need to add dynamic text labels to each region. Any idea how to do this?
2. What is the best way to add a background image?

**Comment by VictorCazanave** [comment]
1. Do you mean how to display the label of the region in the SVG map? 
If so, I don't know how to do that. Maybe you can try to insert a `<text>` element at the right position 🤔 
If you want to display a dynamic tooltip when the mouse is on a region, you can use the [last example of the demo](https://victorcazanave.github.io/react-svg-map/).

2. I think the best way is to define the background image into a `<pattern>` and fill the `<path>` with it. Here is [an example](https://stackoverflow.com/a/3798797/9826498).
However this is currently not (easily) possible with `react-svg-map` component.
If you need it, I can try to add a [slot](https://reactjs.org/docs/composition-vs-inheritance.html#containment) to make it more flexible.

**Comment by VictorCazanave** [comment]
The [contribution guide](https://github.com/VictorCazanave/svg-maps/blob/master/CONTRIBUTING.md) have been updated and slots have been added to [react-svg-map](https://github.com/VictorCazanave/react-svg-map) and [vue-svg-map](https://github.com/VictorCazanave/vue-svg-map).

**Comment by davekedar** [comment]
@bladerunner2020 hello, can you help me with the guide about how to create a new interactive map with svg?

**Comment by bladerunner2020** [comment]
> @bladerunner2020 hello, can you help me with the guide about how to create a new interactive map with svg?

I think you have to ask not me but @VictorCazanave  )))
Though the [guide mentioned above](https://github.com/VictorCazanave/svg-maps/blob/master/CONTRIBUTING.md) is quite straightforward )
