### ISSUE TITLE
What is the license for the actual maps?

### ISSUE THREAD

**Issue by Eric24** [VictorCazanave/svg-maps#37]

**Comment by VictorCazanave** [comment]
This is a very good question and actually I don't know 😅

The original maps come from [different sources](https://github.com/VictorCazanave/svg-maps#sources) and use different licenses (public domain, Creative Commons Attribution-NonCommercial, unknown...). These information are provided in the credits section of each map, but I don't know if the modified maps must use the same license or if it can also be changed (to MIT license for example).

Do you have any idea?

**Comment by Eric24** [comment]
Well, anything that comes from Wikimedia Commons is perfectly fine (under their existing free license). The other two are commercial products, so my take is that anything that is derived from their maps in any way is still a "derivative work" and still subject to their license (so unless you have an agreement with them, you may already be violating their copyright). To know for sure, you'd have to dig deep into their license/copyright. The only exception I can think of is if their maps were derived from "open" sources, but then they would have to (legally) include that license/copyright notice in their maps. Looks like some come from https://www.amcharts.com/svg-maps, and those are fine, too.

**Comment by Eric24** [comment]
PS - I see that MapSVG does state that their maps are freely usable; only their software (Wordpress plugin) is licensed. I couldn't find anything to that effect on simplemaps.

**Comment by VictorCazanave** [comment]
> Well, anything that comes from Wikimedia Commons is perfectly fine (under their existing free license)

OK, I will add the same the license for these maps.

> I see that MapSVG does state that their maps are freely usable; only their software (Wordpress plugin) is licensed.

Yes, I took the "free [to be used] in any custom project" from their website. Today I contacted them to confirm it and ask which license to use.

>  I couldn't find anything to that effect on simplemaps.

This is my mistake. First I used a map for a personal project (which is allowed), then I published it without looking carefully at the license.
I will replace them by maps from another source.

> Looks like some come from https://www.amcharts.com/svg-maps, and those are fine, too.

I forgot this source and I will add the license too.

Thanks a lot for you help! I should have done that long time ago 🙇‍♂️
