### ISSUE TITLE
Missing css file 

### ISSUE THREAD

**Issue by the-wrong-guy** [VictorCazanave/svg-maps#41]
The is no CSS file in the folder 'lib', there is only one SASS file in the src folder

Problem  =>  'Could not find module in path: 'react-svg-map/lib/index.css'

**Comment by VictorCazanave** [comment]
Although this issue is about [react-svg-map](https://github.com/VictorCazanave/react-svg-map) (not svg-maps), thanks for reporting this bug! 
I'll try to fix it today.
