### ISSUE TITLE
Add Austria to Map collection

### ISSUE THREAD

**Issue by Aichnerc** [VictorCazanave/svg-maps#42]
**Is your feature request related to a problem? Please describe.**
Currently, Austria is not implemented.

**Describe the solution you'd like**
Austria should be added to the list. It is a very small country with 9 states and should not take too long to implement.

**Additional context**
Ref.: https://en.wikipedia.org/wiki/Austria

**Comment by VictorCazanave** [comment]
You're right and I think [this map](https://mapsvg.com/maps/austria) may be a good source.
Feel free to create a PR to add it following the [contribution guidelines](https://github.com/VictorCazanave/svg-maps/blob/master/CONTRIBUTING.md)!
