### ISSUE TITLE
 ERROR #98123  WEBPACK Generating development JavaScript bundle failed Can't resolve 'svg-maps' in '/gatsby-project/src/components'

### ISSUE THREAD

**Issue by ziyadbasheer** [VictorCazanave/svg-maps#5]
https://github.com/ziyadbasheer/svg-maps

I've forked the repo, added a map, but can't seem to get it to work:

 ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'svg-maps' in '/gatsby-project/src/components'
File: src/components/worldmap.js
failed Building development bundle - 6.018s

Line in question is: import world from 'svg-maps' within the worldmap.js component.

I've been banging my head against the wall for 3 hours now trying to figure it out. Any help is super appreciated, thanks!

**Comment by VictorCazanave** [comment]
Could you give a link to gatsby-project please?

I tried the [world map](https://github.com/ziyadbasheer/svg-maps/blob/master/packages/world/index.js) you added and it works.

**Comment by ziyadbasheer** [comment]
After hours of struggle I simply copied the package and imported it directly as a component, so no svg-maps, just react-svg-maps, perhaps that should be added as an alternative option in the readme?

Thank you for your great work!

**Comment by VictorCazanave** [comment]
@ziyadbasheer I don't really understand your issue but I'm glad you resolved it 😃 

Just for you information:
* if you want to add a map in svg-maps, you should create a PR (as described in the [contribution guide](https://github.com/VictorCazanave/svg-maps/blob/master/CONTRIBUTING.md)) and wait for it to be merged and published. Then you can install the new map (`npm install --save @svg-maps/new-map`) and import it (`import NewMap from '@svg-maps/new-map'`) in your project to use it with react-svg-map (or another component).
* if you want to use a custom map without adding it to svg-maps, you can create the JS map or generate it with the [svgToJs script](https://github.com/VictorCazanave/svg-maps/blob/master/svgToJs.js), then move the file into your project and import it as any other file to use it with react-svg-map (or another component).

Although it is mentioned in [react-svg-map documentation](https://github.com/VictorCazanave/react-svg-map#usage), it may not be clear enough. So if you have any suggestion to improve the documentation, feel free to create a PR!
