### ISSUE TITLE
Is there a prop to add labels/icons to svg?

### ISSUE THREAD

**Issue by phucmp** [VictorCazanave/svg-maps#62]
I am trying to add span text onto the individual states to indicate States and potentially number of cities. Do you know if there is an easy way to do this?

**Comment by VictorCazanave** [comment]
This repository contains only SVG files and their simplified object representation in JS, so there is no component with props.
Could you open an issue in the right repository ([react-svg-map](https://github.com/VictorCazanave/react-svg-map) or [vue-svg-map](https://github.com/VictorCazanave/vue-svg-map) or ...) please?
