### ISSUE TITLE
Server Error SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by DEVDASTUDIO** [VictorCazanave/svg-maps#85]
Hi,

I'm trying to import France regions in one of my Next.js application and getting this error:

```
Server Error
SyntaxError: Unexpected token 'export'

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
external%20%22@svg-maps/france.regions%22 (1:0) @ eval

> 1 | module.exports = require("@svg-maps/france.regions");

```

My component
```
import React, {useEffect,useState} from 'react'

import France from '@svg-maps/france.regions';
import { SVGMap } from "react-svg-map";
import "react-svg-map/lib/index.css";

const Home = ({properties}) => {
        const [show, setShow] = useState(false);
         const handleClose = () => setShow(false);
return (
 <SVGMap map={France} />
 )
 }````



 next.config.js file in root 



 ```const withPWA = require('next-pwa')
const runtimeCaching = require('next-pwa/cache')
const path = require('path');
const withImages = require('next-images')

//https://github.com/shadowwalker/next-pwa
module.exports = withPWA(withImages({
  pwa: {
    disable: true,//process.env.NODE_ENV === 'development',
    dest: 'public',
    runtimeCaching,
  },
  exclude: path.resolve(__dirname, 'src/assets/svg'),
  webpack(config, options) {
    return config
  }
}))```

**Comment by DEVDASTUDIO** [comment]
I changed file in @svg-maps/france.regions/index.js
```export default``` to ```module.exports =``

**Comment by VictorCazanave** [comment]
I've never used Next.js but it looks like you're trying to import a CommonJS module and this repository provides only ES modules.

If needed, an `index.cjs.js` could also be generated for each map.

**Comment by DEVDASTUDIO** [comment]
Thank you for your quick response.
I created a my own svg js file as france.departments.js and it is working.

`module.exports = {"label":"Map of France departments","viewBox":"0 0 613 585","locations": ...`

**Comment by DEVDASTUDIO** [comment]
No it is not working, it throw error: TypeError: Cannot read property 'id' of undefined
    at /Users/xyz/Sites/project/node_modules/react-svg-map/lib/index.js:1:1394

**Comment by DEVDASTUDIO** [comment]
How can I generate `index.cjs.jsz` file?

**Comment by VictorCazanave** [comment]
The script [svgToJs.js](https://github.com/VictorCazanave/svg-maps/blob/master/svgToJs.js) must be modified and run for all the maps to publish the CommonJS versions.

I don't know when I have time to work on that, so if you know how to do it, feel free to create a pull request!

**Comment by henriklundgren** [comment]
Try using https://www.npmjs.com/package/next-transpile-modules

**Comment by DannyM1chael** [comment]
> Try using https://www.npmjs.com/package/next-transpile-modules

Thanks, it helped!

**Comment by MattHeslington** [comment]
> Try using https://www.npmjs.com/package/next-transpile-modules

To do what - could you explain a little please - I'm having the same issue as the original poster and I'd love to get this working in Next

**Comment by henriklundgren** [comment]
@MattHeslington It should be self-explanatory. You create a `next.config.js` , require the `next-transpile-modules` and wrap the `@svg-maps/foo` just as explained in the readme.

Example:

```js
const withTM = require('next-transpile-modules')(['@svg-maps/indonesia']);
```

**Comment by MattHeslington** [comment]
@henriklundgren Thanks Henrik. Your original answer implied next-transpile-mudules should be used with svgToJs.js - hence the question.
