### ISSUE TITLE
@svg-maps/cli binary does not exist

### ISSUE THREAD

**Issue by Frozen-byte** [VictorCazanave/svg-maps#91]
When I use `npm install @svg-maps/cli`  there is no svg-maps binary created in `node_modules/.bin` that I am able to use.

Tried with version `^1.0.0-beta.2` on Linux and Windows.

**Comment by Frozen-byte** [comment]
https://github.com/VictorCazanave/svg-maps/blob/master/CONTRIBUTING.md seems outdated, too: package.json does not have any "build" script.

**Comment by KingoftheRoad** [comment]
I met the same problem. Anyone can help?

**Comment by VictorCazanave** [comment]
Thank you for reporting this issue!
I'm pretty busy recently, but I'll try to have a look this week.

**Comment by KingoftheRoad** [comment]
thank you!

**Comment by Frozen-byte** [comment]
Oh and btw: It would be **awesome** to make the app `npx` compatible.
Simply using `npx source.svg target.js` without dev-installation <3

Should be possible, if the project default `npm run` will point to the binary.

**Comment by VictorCazanave** [comment]
@Frozen-byte @KingoftheRoad this issue should be fixed now:
- binary has been added
- outdated documentation has been updated

If it's still not usable, feel free to reopen it!

> Oh and btw: It would be awesome to make the app npx compatible.
Simply using npx source.svg target.js without dev-installation <3
Should be possible, if the project default npm run will point to the binary.

I'm not sure if I really understood your request, but you can use it without installation with `npx @svg-maps/cli [command]`.
If this is not what you expected, feel free to open a new issue or a PR!
